# config.yaml

# Core Training Parameters
epochs: 100
batch_size: 2              # Per-GPU batch size
devices: 2                 # Number of GPUs to use
lr: 0.0001
seed: 42

# Batch Size Math
target_effective_batch_size: 16

# Model Settings
use_ema: true
checkpoint_interval: 10
skip_best_epochs: 3

# Early Stopping
early_stopping: true
early_stopping_patience: 10
early_stopping_min_delta: 0.005
early_stopping_use_ema: true

# # Logging & Evaluation - 
# # These are currently missing from the training scripts!
# tensorboard: false
# eval_interval: 4
# log_per_class_metrics: true